package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1



/**
 * GastoloteboiId generated by hbm2java
 */
public class GastoloteboiId  implements java.io.Serializable {


     private int gbLbCodigo;
     private int gbGastoCodigo;

    public GastoloteboiId() {
    }

    public GastoloteboiId(int gbLbCodigo, int gbGastoCodigo) {
       this.gbLbCodigo = gbLbCodigo;
       this.gbGastoCodigo = gbGastoCodigo;
    }
   
    public int getGbLbCodigo() {
        return this.gbLbCodigo;
    }
    
    public void setGbLbCodigo(int gbLbCodigo) {
        this.gbLbCodigo = gbLbCodigo;
    }
    public int getGbGastoCodigo() {
        return this.gbGastoCodigo;
    }
    
    public void setGbGastoCodigo(int gbGastoCodigo) {
        this.gbGastoCodigo = gbGastoCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GastoloteboiId) ) return false;
		 GastoloteboiId castOther = ( GastoloteboiId ) other; 
         
		 return (this.getGbLbCodigo()==castOther.getGbLbCodigo())
 && (this.getGbGastoCodigo()==castOther.getGbGastoCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGbLbCodigo();
         result = 37 * result + this.getGbGastoCodigo();
         return result;
   }   


}


