package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private Integer gastoCodigo;
     private Produto produto;
     private Date gastoData;
     private BigDecimal gastoValor;
     private Integer gastoQteComprada;
     private Set gastolotebois = new HashSet(0);

    public Gasto() {
    }

	
    public Gasto(BigDecimal gastoValor) {
        this.gastoValor = gastoValor;
    }
    public Gasto(Produto produto, Date gastoData, BigDecimal gastoValor, Integer gastoQteComprada, Set gastolotebois) {
       this.produto = produto;
       this.gastoData = gastoData;
       this.gastoValor = gastoValor;
       this.gastoQteComprada = gastoQteComprada;
       this.gastolotebois = gastolotebois;
    }
   
    public Integer getGastoCodigo() {
        return this.gastoCodigo;
    }
    
    public void setGastoCodigo(Integer gastoCodigo) {
        this.gastoCodigo = gastoCodigo;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Date getGastoData() {
        return this.gastoData;
    }
    
    public void setGastoData(Date gastoData) {
        this.gastoData = gastoData;
    }
    public BigDecimal getGastoValor() {
        return this.gastoValor;
    }
    
    public void setGastoValor(BigDecimal gastoValor) {
        this.gastoValor = gastoValor;
    }
    public Integer getGastoQteComprada() {
        return this.gastoQteComprada;
    }
    
    public void setGastoQteComprada(Integer gastoQteComprada) {
        this.gastoQteComprada = gastoQteComprada;
    }
    public Set getGastolotebois() {
        return this.gastolotebois;
    }
    
    public void setGastolotebois(Set gastolotebois) {
        this.gastolotebois = gastolotebois;
    }




}


