package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer loginCodigo;
     private String loginNome;
     private String loginSenha;

    public Login() {
    }

    public Login(String loginNome, String loginSenha) {
       this.loginNome = loginNome;
       this.loginSenha = loginSenha;
    }
   
    public Integer getLoginCodigo() {
        return this.loginCodigo;
    }
    
    public void setLoginCodigo(Integer loginCodigo) {
        this.loginCodigo = loginCodigo;
    }
    public String getLoginNome() {
        return this.loginNome;
    }
    
    public void setLoginNome(String loginNome) {
        this.loginNome = loginNome;
    }
    public String getLoginSenha() {
        return this.loginSenha;
    }
    
    public void setLoginSenha(String loginSenha) {
        this.loginSenha = loginSenha;
    }




}


