package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loteboi generated by hbm2java
 */
public class Loteboi  implements java.io.Serializable {


     private Integer lbCodigo;
     private Pasto pasto;
     private Date lbData;
     private BigDecimal lbValor;
     private String lbVend;
     private int lbQteCab;
     private Set gastolotebois = new HashSet(0);
     private Set vendaUnidades = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Loteboi() {
    }

	
    public Loteboi(BigDecimal lbValor, String lbVend, int lbQteCab) {
        this.lbValor = lbValor;
        this.lbVend = lbVend;
        this.lbQteCab = lbQteCab;
    }
    public Loteboi(Pasto pasto, Date lbData, BigDecimal lbValor, String lbVend, int lbQteCab, Set gastolotebois, Set vendaUnidades, Set vendas) {
       this.pasto = pasto;
       this.lbData = lbData;
       this.lbValor = lbValor;
       this.lbVend = lbVend;
       this.lbQteCab = lbQteCab;
       this.gastolotebois = gastolotebois;
       this.vendaUnidades = vendaUnidades;
       this.vendas = vendas;
    }
   
    public Integer getLbCodigo() {
        return this.lbCodigo;
    }
    
    public void setLbCodigo(Integer lbCodigo) {
        this.lbCodigo = lbCodigo;
    }
    public Pasto getPasto() {
        return this.pasto;
    }
    
    public void setPasto(Pasto pasto) {
        this.pasto = pasto;
    }
    public Date getLbData() {
        return this.lbData;
    }
    
    public void setLbData(Date lbData) {
        this.lbData = lbData;
    }
    public BigDecimal getLbValor() {
        return this.lbValor;
    }
    
    public void setLbValor(BigDecimal lbValor) {
        this.lbValor = lbValor;
    }
    public String getLbVend() {
        return this.lbVend;
    }
    
    public void setLbVend(String lbVend) {
        this.lbVend = lbVend;
    }
    public int getLbQteCab() {
        return this.lbQteCab;
    }
    
    public void setLbQteCab(int lbQteCab) {
        this.lbQteCab = lbQteCab;
    }
    public Set getGastolotebois() {
        return this.gastolotebois;
    }
    
    public void setGastolotebois(Set gastolotebois) {
        this.gastolotebois = gastolotebois;
    }
    public Set getVendaUnidades() {
        return this.vendaUnidades;
    }
    
    public void setVendaUnidades(Set vendaUnidades) {
        this.vendaUnidades = vendaUnidades;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


