package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pasto generated by hbm2java
 */
public class Pasto  implements java.io.Serializable {


     private Integer pastoCodigo;
     private String pastoDono;
     private BigDecimal valorPorCabeca;
     private BigDecimal pastoAluguel;
     private String pastoTempoLocacao;
     private Date pastoDatainicioLocacao;
     private Date pastoDatafinalLocacao;
     private Set lotebois = new HashSet(0);

    public Pasto() {
    }

	
    public Pasto(String pastoDono, BigDecimal valorPorCabeca, BigDecimal pastoAluguel, String pastoTempoLocacao) {
        this.pastoDono = pastoDono;
        this.valorPorCabeca = valorPorCabeca;
        this.pastoAluguel = pastoAluguel;
        this.pastoTempoLocacao = pastoTempoLocacao;
    }
    public Pasto(String pastoDono, BigDecimal valorPorCabeca, BigDecimal pastoAluguel, String pastoTempoLocacao, Date pastoDatainicioLocacao, Date pastoDatafinalLocacao, Set lotebois) {
       this.pastoDono = pastoDono;
       this.valorPorCabeca = valorPorCabeca;
       this.pastoAluguel = pastoAluguel;
       this.pastoTempoLocacao = pastoTempoLocacao;
       this.pastoDatainicioLocacao = pastoDatainicioLocacao;
       this.pastoDatafinalLocacao = pastoDatafinalLocacao;
       this.lotebois = lotebois;
    }
   
    public Integer getPastoCodigo() {
        return this.pastoCodigo;
    }
    
    public void setPastoCodigo(Integer pastoCodigo) {
        this.pastoCodigo = pastoCodigo;
    }
    public String getPastoDono() {
        return this.pastoDono;
    }
    
    public void setPastoDono(String pastoDono) {
        this.pastoDono = pastoDono;
    }
    public BigDecimal getValorPorCabeca() {
        return this.valorPorCabeca;
    }
    
    public void setValorPorCabeca(BigDecimal valorPorCabeca) {
        this.valorPorCabeca = valorPorCabeca;
    }
    public BigDecimal getPastoAluguel() {
        return this.pastoAluguel;
    }
    
    public void setPastoAluguel(BigDecimal pastoAluguel) {
        this.pastoAluguel = pastoAluguel;
    }
    public String getPastoTempoLocacao() {
        return this.pastoTempoLocacao;
    }
    
    public void setPastoTempoLocacao(String pastoTempoLocacao) {
        this.pastoTempoLocacao = pastoTempoLocacao;
    }
    public Date getPastoDatainicioLocacao() {
        return this.pastoDatainicioLocacao;
    }
    
    public void setPastoDatainicioLocacao(Date pastoDatainicioLocacao) {
        this.pastoDatainicioLocacao = pastoDatainicioLocacao;
    }
    public Date getPastoDatafinalLocacao() {
        return this.pastoDatafinalLocacao;
    }
    
    public void setPastoDatafinalLocacao(Date pastoDatafinalLocacao) {
        this.pastoDatafinalLocacao = pastoDatafinalLocacao;
    }
    public Set getLotebois() {
        return this.lotebois;
    }
    
    public void setLotebois(Set lotebois) {
        this.lotebois = lotebois;
    }




}


