package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer venCodigo;
     private Loteboi loteboi;
     private String venComprador;
     private Date venData;
     private BigDecimal venValor;
     private String venTipoPagm;
     private int venQteCabeca;
     private BigDecimal venLucro;

    public Venda() {
    }

	
    public Venda(String venComprador, BigDecimal venValor, String venTipoPagm, int venQteCabeca, BigDecimal venLucro) {
        this.venComprador = venComprador;
        this.venValor = venValor;
        this.venTipoPagm = venTipoPagm;
        this.venQteCabeca = venQteCabeca;
        this.venLucro = venLucro;
    }
    public Venda(Loteboi loteboi, String venComprador, Date venData, BigDecimal venValor, String venTipoPagm, int venQteCabeca, BigDecimal venLucro) {
       this.loteboi = loteboi;
       this.venComprador = venComprador;
       this.venData = venData;
       this.venValor = venValor;
       this.venTipoPagm = venTipoPagm;
       this.venQteCabeca = venQteCabeca;
       this.venLucro = venLucro;
    }
   
    public Integer getVenCodigo() {
        return this.venCodigo;
    }
    
    public void setVenCodigo(Integer venCodigo) {
        this.venCodigo = venCodigo;
    }
    public Loteboi getLoteboi() {
        return this.loteboi;
    }
    
    public void setLoteboi(Loteboi loteboi) {
        this.loteboi = loteboi;
    }
    public String getVenComprador() {
        return this.venComprador;
    }
    
    public void setVenComprador(String venComprador) {
        this.venComprador = venComprador;
    }
    public Date getVenData() {
        return this.venData;
    }
    
    public void setVenData(Date venData) {
        this.venData = venData;
    }
    public BigDecimal getVenValor() {
        return this.venValor;
    }
    
    public void setVenValor(BigDecimal venValor) {
        this.venValor = venValor;
    }
    public String getVenTipoPagm() {
        return this.venTipoPagm;
    }
    
    public void setVenTipoPagm(String venTipoPagm) {
        this.venTipoPagm = venTipoPagm;
    }
    public int getVenQteCabeca() {
        return this.venQteCabeca;
    }
    
    public void setVenQteCabeca(int venQteCabeca) {
        this.venQteCabeca = venQteCabeca;
    }
    public BigDecimal getVenLucro() {
        return this.venLucro;
    }
    
    public void setVenLucro(BigDecimal venLucro) {
        this.venLucro = venLucro;
    }




}


