package pojo;
// Generated 06/01/2015 21:06:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VendaUnidade generated by hbm2java
 */
public class VendaUnidade  implements java.io.Serializable {


     private Integer vendaUnidadeId;
     private Loteboi loteboi;
     private int vendaUnidadeQuantidade;
     private String vendaUnidadeComprador;
     private Date vendaUnidadeData;
     private String vendaUnidadeTipoPagamento;
     private Double vedaLucroObtido;
     private Double vendaUnidadeValorVenda;

    public VendaUnidade() {
    }

	
    public VendaUnidade(Loteboi loteboi, int vendaUnidadeQuantidade) {
        this.loteboi = loteboi;
        this.vendaUnidadeQuantidade = vendaUnidadeQuantidade;
    }
    public VendaUnidade(Loteboi loteboi, int vendaUnidadeQuantidade, String vendaUnidadeComprador, Date vendaUnidadeData, String vendaUnidadeTipoPagamento, Double vedaLucroObtido, Double vendaUnidadeValorVenda) {
       this.loteboi = loteboi;
       this.vendaUnidadeQuantidade = vendaUnidadeQuantidade;
       this.vendaUnidadeComprador = vendaUnidadeComprador;
       this.vendaUnidadeData = vendaUnidadeData;
       this.vendaUnidadeTipoPagamento = vendaUnidadeTipoPagamento;
       this.vedaLucroObtido = vedaLucroObtido;
       this.vendaUnidadeValorVenda = vendaUnidadeValorVenda;
    }
   
    public Integer getVendaUnidadeId() {
        return this.vendaUnidadeId;
    }
    
    public void setVendaUnidadeId(Integer vendaUnidadeId) {
        this.vendaUnidadeId = vendaUnidadeId;
    }
    public Loteboi getLoteboi() {
        return this.loteboi;
    }
    
    public void setLoteboi(Loteboi loteboi) {
        this.loteboi = loteboi;
    }
    public int getVendaUnidadeQuantidade() {
        return this.vendaUnidadeQuantidade;
    }
    
    public void setVendaUnidadeQuantidade(int vendaUnidadeQuantidade) {
        this.vendaUnidadeQuantidade = vendaUnidadeQuantidade;
    }
    public String getVendaUnidadeComprador() {
        return this.vendaUnidadeComprador;
    }
    
    public void setVendaUnidadeComprador(String vendaUnidadeComprador) {
        this.vendaUnidadeComprador = vendaUnidadeComprador;
    }
    public Date getVendaUnidadeData() {
        return this.vendaUnidadeData;
    }
    
    public void setVendaUnidadeData(Date vendaUnidadeData) {
        this.vendaUnidadeData = vendaUnidadeData;
    }
    public String getVendaUnidadeTipoPagamento() {
        return this.vendaUnidadeTipoPagamento;
    }
    
    public void setVendaUnidadeTipoPagamento(String vendaUnidadeTipoPagamento) {
        this.vendaUnidadeTipoPagamento = vendaUnidadeTipoPagamento;
    }
    public Double getVedaLucroObtido() {
        return this.vedaLucroObtido;
    }
    
    public void setVedaLucroObtido(Double vedaLucroObtido) {
        this.vedaLucroObtido = vedaLucroObtido;
    }
    public Double getVendaUnidadeValorVenda() {
        return this.vendaUnidadeValorVenda;
    }
    
    public void setVendaUnidadeValorVenda(Double vendaUnidadeValorVenda) {
        this.vendaUnidadeValorVenda = vendaUnidadeValorVenda;
    }




}


